# Site settings
title: youbingtiantian
SEOTitle: 油饼甜甜 | ybtt blog
header-img: img/home-bg.jpg
email: 1277765452@qq.com
description: "关于油饼甜甜的博客..."
keyword: ""
url: "https://youbingtiantian.github.io" # your host, for absolute URL
baseurl: "/youbingtiantian.github.io" # for example, '/blog' if your blog hosted on 'host/blog'

# SNS settings
RSS: false
weibo_username: 油饼沺沺
zhihu_username: 油饼沺沺
github_username: youbingtiantian

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important

# Sidebar settings
sidebar: true # 开启侧边栏
sidebar-about-description: "天意不可违" # 侧边栏的一个描述
sidebar-avatar: /img/avatar-ybtt.jpg # 侧边栏的一个头像

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Friends 友情链接
# friends:
#   [
#     { title: "Hux Blog", href: "http://huangxuan.me" },
#     { title: "Foo", href: "#" },
#     { title: "Bar", href: "#" },
#     { title: "Example Friends", href: "#" },
#     { title: "It helps SEO", href: "#" },
#   ]
